#Lista de sitios donde me gustaría ir

locations = ["Roma", "Tokyo", "Atenas", "Viena", "Budapest"]
print ("Aquí está mi lista de sitios donde me gustaría ir: ")
print (locations)
print ("\nAquí está mi lista de sitios donde me gustaría ir ordenado alfabéticamente: ")
print (sorted(locations))
print ("\nAquí la lista sin modificar: ")
print (locations)
print ("\nAquí la lista ordenada alfabéticamente inversa: ")
print (sorted(locations, reverse=True))
print ("\nAquí la lista otra vez sin cambios: ")
print (locations)
print ("\nAquí la lista invertida con cambios permanentes: ")
locations.reverse()
print (locations)
print ("\nAhora volvemos a mostrar la lista invertida otra vez, que será como la original: ")
locations.reverse()
print (locations)
print ("\nAhora la lista ordenada alfabéticamente con cambios permanentes: ")
locations.sort()
print (locations)
print ("\nAhora la lista ordenada alfabéticamente a la inversa con cambios permanentes: ")
locations.sort(reverse=True)
print (locations)